ADDITIONAL_TOOL_LIBS += \
		-lTMill \


ADDITIONAL_GUI_LIBS += \
		-lTMill \
		-lTMillGUI \
		-lTMillPaletteGUI \


ADDITIONAL_INCLUDE_DIRS += \
		-ITMLib \
		-ITMKit \
		-ITMPaletteKit \


ADDITIONAL_LIB_DIRS += \
		-LTMLib/$(GNUSTEP_OBJ_DIR) \
		-LTMKit/$(GNUSTEP_OBJ_DIR) \
		-LTMPaletteKit/$(GNUSTEP_OBJ_DIR) \
